# permissions for end users to edit automatedclusterdiscoveries.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: automatedclusterdiscovery-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: cluster-reflector-controller
    app.kubernetes.io/part-of: cluster-reflector-controller
    app.kubernetes.io/managed-by: kustomize
  name: automatedclusterdiscovery-editor-role
rules:
- apiGroups:
  - clusters.weave.works
  resources:
  - automatedclusterdiscoveries
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - clusters.weave.works
  resources:
  - automatedclusterdiscoveries/status
  verbs:
  - get
